---
title: "mapa stations use"
author: "edu"
date: "2025-02-01"
output: html_document
---

# mapa stations use - 1
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)
library(leaflet)
library(mapview)
library(htmlwidgets)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Create a Leaflet map
leaflet_map <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = n_sf, color = "black", weight = 0.5, fillColor = "white", fillOpacity = 0.5) %>%
  addCircleMarkers(data = stations_sf,
                   color = ~colorNumeric(palette = c("#FFCDD2", "#8B0000"), domain = stations_sf$daily_avg_input_output)(daily_avg_input_output),
                   radius = ~scales::rescale(daily_avg_input_output, to = c(0.5, 5)),
                   stroke = FALSE, fillOpacity = 0.7)

# Save the Leaflet map as an HTML file
saveWidget(leaflet_map, "stations_daily_avg_input_output.html", selfcontained = TRUE)

# Create a plot with daily_avg_input_output represented by a red color scale and proportional use radius
plot_daily_avg_input_output <- ggplot() +
  geom_sf(data = n_sf, color = alpha("black", 0.5), fill = "white", size = 0.2) +
  geom_sf(data = stations_sf, aes(color = daily_avg_input_output, size = daily_avg_input_output), alpha = 0.7, stroke = 0.1, fill = "white") +
  scale_color_gradient(low = "#FFCDD2", high = "#8B0000", name = "Daily Avg Input-Output") +
  scale_size_continuous(range = c(0.5, 5), name = "Proportional Use Radius") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Bicing Stations in Barcelona by Daily Average Use Input-Output"
  ) +
  annotation_custom(
    grob = textGrob(
      label = "Data source: Bicing and Barcelona Open Data",
      x = unit(1, "npc") - unit(1, "lines"),
      y = unit(0, "npc") + unit(1, "lines"),
      just = c("right", "bottom"),
      gp = gpar(fontsize = 8, col = "black")
    )
  )

# Save the plot as a PNG file
ggsave("stations_daily_avg_input_output.png", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")

# Save the plot as a JPG file
ggsave("stations_daily_avg_input_output.jpg", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")
```





# A. First, save the Leaflet map as an image using the mapview package: ESTA FUNCIONABA CON POCA RESO
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)
library(leaflet)
library(htmlwidgets)
library(mapview)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Create a Leaflet map
leaflet_map <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = n_sf, color = "black", weight = 0.5, fillColor = "white", fillOpacity = 0.2) %>%
  addCircleMarkers(data = stations_sf,
                   color = ~colorNumeric(palette = c("#FFCDD2", "#8B0000"), domain = stations_sf$daily_avg_input_output)(daily_avg_input_output),
                   radius = ~scales::rescale(daily_avg_input_output, to = c(0.5, 5)),
                   stroke = FALSE, fillOpacity = 0.7)

# Save the Leaflet map as an HTML file
saveWidget(leaflet_map, "stations_daily_avg_input_output.html", selfcontained = TRUE)

# Save the Leaflet map as an image
mapshot(leaflet_map, file = "leaflet_map.png")
```



# A. nueva
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)
library(leaflet)
library(htmlwidgets)
library(mapview)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Create a Leaflet map
leaflet_map <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = n_sf, color = "black", weight = 0.5, fillColor = "white", fillOpacity = 0.2) %>%
  addCircleMarkers(data = stations_sf,
                   color = ~colorNumeric(palette = c("#FFCDD2", "#8B0000"), domain = stations_sf$daily_avg_input_output)(daily_avg_input_output),
                   radius = ~scales::rescale(daily_avg_input_output, to = c(0.5, 5)),
                   stroke = FALSE, fillOpacity = 0.7)

# Save the Leaflet map as an HTML file
saveWidget(leaflet_map, "stations_daily_avg_input_output.html", selfcontained = TRUE)

# Save the Leaflet map as an image
mapshot(leaflet_map, file = "leaflet_map.png")
```





# B. First, save the Leaflet map as an image using the mapview package:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(png)
library(grid)

# Read the saved Leaflet map image
leaflet_map_img <- readPNG("leaflet_map.png")

# Create a plot with daily_avg_input_output represented by a red color scale and proportional use radius
plot_daily_avg_input_output <- ggplot() +
  annotation_custom(rasterGrob(leaflet_map_img, width = unit(1, "npc"), height = unit(1, "npc")), -Inf, Inf, -Inf, Inf) +
  geom_sf(data = n_sf, color = alpha("black", 0.5), fill = alpha("white", 0.2), size = 0.2) +
  geom_sf(data = stations_sf, aes(color = daily_avg_input_output, size = daily_avg_input_output), alpha = 0.7, stroke = 0.1, fill = alpha("white", 0.2)) +
  scale_color_gradient(low = "#FFCDD2", high = "#8B0000", name = "Daily Avg Input-Output") +
  scale_size_continuous(range = c(0.5, 5), name = "Proportional Use Radius") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = alpha("white", 0.2), color = alpha("white", 0.2)),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Bicing Stations in Barcelona by Daily Average Use Input-Output"
  ) +
  annotation_custom(
    grob = textGrob(
      label = "Data source: Bicing and Barcelona Open Data",
      x = unit(1, "npc") - unit(1, "lines"),
      y = unit(0, "npc") + unit(1, "lines"),
      just = c("right", "bottom"),
      gp = gpar(fontsize = 8, col = "black")
    )
  )

# Save the plot as a PNG file
ggsave("stations_daily_avg_input_output.png", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")

# Save the plot as a JPG file
ggsave("stations_daily_avg_input_output.jpg", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")
```
















# mapa stations use - clean TOP 50
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Identify the top 50 stations by daily_avg_input_output
top_50_stations <- stations_info_use %>%
  arrange(desc(daily_avg_input_output)) %>%
  head(50)

top_50_stations_sf <- st_as_sf(top_50_stations, coords = c("lon", "lat"), crs = 4326)

# Create a plot with daily_avg_input_output represented by a red color scale and proportional use radius
plot_daily_avg_input_output <- ggplot() +
  geom_sf(data = n_sf, color = alpha("black", 0.5), fill = "white", size = 0.2) +
  geom_sf(data = stations_sf, aes(color = daily_avg_input_output, size = daily_avg_input_output), alpha = 0.7, stroke = 0.1, fill = "white") +
  geom_sf(data = top_50_stations_sf, aes(size = daily_avg_input_output), color = "#8B0000", fill = "#8B0000", shape = 21, alpha = 1) +
  scale_color_gradient(low = "#FFCDD2", high = "#8B0000", name = "Daily Avg Input-Output") +
  scale_size_continuous(range = c(0.5, 5), name = "Proportional Use Radius") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Bicing Stations in Barcelona by Daily Average Use Input-Output - Top 50 used station in solid red"
  ) +
  annotation_custom(
    grob = textGrob(
      label = "Data source: Bicing and Barcelona Open Data",
      x = unit(1, "npc") - unit(1, "lines"),
      y = unit(0, "npc") + unit(1, "lines"),
      just = c("right", "bottom"),
      gp = gpar(fontsize = 8, col = "black")
    )
  )

# Save the plot as a PNG file
ggsave("stations_daily_avg_input_output_50.png", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")

# Save the plot as a JPG file
ggsave("stations_daily_avg_input_output_50.jpg", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")
```



# mapa stations use - clean TOP 100
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Identify the top 50 stations by daily_avg_input_output
top_100_stations <- stations_info_use %>%
  arrange(desc(daily_avg_input_output)) %>%
  head(100)

top_100_stations_sf <- st_as_sf(top_100_stations, coords = c("lon", "lat"), crs = 4326)

# Create a plot with daily_avg_input_output represented by a red color scale and proportional use radius
plot_daily_avg_input_output <- ggplot() +
  geom_sf(data = n_sf, color = alpha("black", 0.5), fill = "white", size = 0.2) +
  geom_sf(data = stations_sf, aes(color = daily_avg_input_output, size = daily_avg_input_output), alpha = 0.7, stroke = 0.1, fill = "white") +
  geom_sf(data = top_100_stations_sf, aes(size = daily_avg_input_output), color = "#8B0000", fill = "#8B0000", shape = 21, alpha = 1) +
  scale_color_gradient(low = "#FFCDD2", high = "#8B0000", name = "Daily Avg Input-Output") +
  scale_size_continuous(range = c(0.5, 5), name = "Proportional Use Radius") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Bicing Stations in Barcelona by Daily Average Use Input-Output - Top 100 used station in solid red"
  ) +
  annotation_custom(
    grob = textGrob(
      label = "Data source: Bicing and Barcelona Open Data",
      x = unit(1, "npc") - unit(1, "lines"),
      y = unit(0, "npc") + unit(1, "lines"),
      just = c("right", "bottom"),
      gp = gpar(fontsize = 8, col = "black")
    )
  )

# Save the plot as a PNG file
ggsave("stations_daily_avg_input_output_100.png", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")

# Save the plot as a JPG file
ggsave("stations_daily_avg_input_output_100.jpg", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")
```


# mapa stations use - clean TOP 150
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Identify the top 150 stations by daily_avg_input_output
top_150_stations <- stations_info_use %>%
  arrange(desc(daily_avg_input_output)) %>%
  head(150)

top_150_stations_sf <- st_as_sf(top_150_stations, coords = c("lon", "lat"), crs = 4326)

# Create a plot with daily_avg_input_output represented by a red color scale and proportional use radius
plot_daily_avg_input_output <- ggplot() +
  geom_sf(data = n_sf, color = alpha("black", 0.5), fill = "white", size = 0.2) +
  geom_sf(data = stations_sf, aes(color = daily_avg_input_output, size = daily_avg_input_output), alpha = 0.7, stroke = 0.1, fill = "white") +
  geom_sf(data = top_150_stations_sf, aes(size = daily_avg_input_output), color = "#8B0000", fill = "#8B0000", shape = 21, alpha = 1) +
  scale_color_gradient(low = "#FFCDD2", high = "#8B0000", name = "Daily Avg Input-Output") +
  scale_size_continuous(range = c(0.5, 5), name = "Proportional Use Radius") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Bicing Stations in Barcelona by Daily Average Use Input-Output - Top 150 used station in solid red"
  ) +
  annotation_custom(
    grob = textGrob(
      label = "Data source: Bicing and Barcelona Open Data",
      x = unit(1, "npc") - unit(1, "lines"),
      y = unit(0, "npc") + unit(1, "lines"),
      just = c("right", "bottom"),
      gp = gpar(fontsize = 8, col = "black")
    )
  )

# Save the plot as a PNG file
ggsave("stations_daily_avg_input_output_150.png", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")

# Save the plot as a JPG file
ggsave("stations_daily_avg_input_output_150.jpg", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")
```




# mapa stations use - clean ABOVE AVG
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary libraries
library(sf)
library(dplyr)
library(ggplot2)
library(grid)

# Convert stations_info_use to sf object
stations_sf <- st_as_sf(stations_info_use, coords = c("lon", "lat"), crs = 4326)

# Calculate the average daily_avg_input_output
avg_daily_avg_input_output <- mean(stations_info_use$daily_avg_input_output, na.rm = TRUE)

# Identify the stations with daily_avg_input_output above the average
above_avg_stations <- stations_info_use %>%
  filter(daily_avg_input_output > avg_daily_avg_input_output)

above_avg_stations_sf <- st_as_sf(above_avg_stations, coords = c("lon", "lat"), crs = 4326)

# Create a plot with daily_avg_input_output represented by a red color scale and proportional use radius
plot_daily_avg_input_output <- ggplot() +
  geom_sf(data = n_sf, color = alpha("black", 0.5), fill = "white", size = 0.2) +
  geom_sf(data = stations_sf, aes(color = daily_avg_input_output, size = daily_avg_input_output), alpha = 0.7, stroke = 0.1, fill = "white") +
  geom_sf(data = above_avg_stations_sf, aes(size = daily_avg_input_output), color = "#8B0000", fill = "#8B0000", shape = 21, alpha = 1) +
  scale_color_gradient(low = "#FFCDD2", high = "#8B0000", name = "Daily Avg Input-Output") +
  scale_size_continuous(range = c(0.5, 5), name = "Proportional Use Radius") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "white", color = "white"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Bicing Stations in Barcelona by Daily Average Use Input-Output - Above Average Use in Solid Red"
  ) +
  annotation_custom(
    grob = textGrob(
      label = "Data source: Bicing and Barcelona Open Data",
      x = unit(1, "npc") - unit(1, "lines"),
      y = unit(0, "npc") + unit(1, "lines"),
      just = c("right", "bottom"),
      gp = gpar(fontsize = 8, col = "black")
    )
  )

# Save the plot as a PNG file
ggsave("stations_daily_avg_input_output_above_avg.png", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")

# Save the plot as a JPG file
ggsave("stations_daily_avg_input_output_above_avg.jpg", plot = plot_daily_avg_input_output, width = 10, height = 10, dpi = 300, bg = "white")
```






